---
renown:
  achievements:
    renown_leading:
      type: story
      message: Was announced as leading in the specified time span in the regular
        bbpost.
    renown_favorite:
      type: story
      message: Overall leader at the end of the season.
  cron_message_title: Favorite of the Week
  cron_renown_days: 7
  cron_regular_check:
    day_of_week:
    - Sun
    hour:
    - 12
    minute:
    - 34
  cron_message_category: Announcements
  renown_fields:
  - field: name
    width: 28
    title: Name
  - field: gained
    width: 10
    title: Renown Gained
  - field: group
    value: house
    width: 18
    title: House
  - field: rank
    width: 18
    title: Rank
  renown_group: house
  renown_members:
  - group: faction
    value: Noble
  renown_title: Renown
  shortcuts: {}
  standard_types:
  - type: Freeform
    points: 0
  - type: Minor Scandal
    points: -50
  - type: Major Scandal
    points: -150
  - type: Single Contest Winner
    points: 200
  - type: Overall Contest Winner
    points: 500
  - type: Fitting Remark
    points: 50
  - type: Courageous Statement
    points: 100
  visible: true
  web_renown_total_fields:
  - field: group
    value: house
    title: House
  - field: group
    value: rank
    title: Rank
